### PR TITLE
Tests in sdist

### PR DESCRIPTION
**Pull request by rvl**
Hi, I'm packaging python-mpd2 for Nix. It would be helpful if the tests were included in the source distribution so integration tests can be run for the module. Cheers.

### CODE REVIEW

**Comment by Mic92** [comment]
Merged thanks.

**Comment by rvl** [comment]
Thanks. Just checking, when do you plan to make a new release to PyPI? I.e. should I wait for v0.55.0 before submitting python-mpd2 and Sonata to Nix, or submit v0.54.0 with tests disabled and update later.

**Comment by Mic92** [comment]
I just create a release v0.5.5 with your changes included

**Comment by rvl** [comment]
Excellent! FYI: NixOS/nixpkgs#12720

**Pull request merged**
