### PR TITLE
clarify when methods return something

### PR DESCRIPTION
**Pull request by DivineDominion**
When reading the docs, I wasn't quite sure if e.g. "Displays xyz" entails that the method call itself already prints the results. I replaced "displays", "dumps" and other verbs that misleadingly sound like command executions instead of return values with "returns".

### CODE REVIEW

**Comment by Mic92** [comment]
This file was currently generated from the upstream protocol documentation:

 https://github.com/Mic92/python-mpd2/blob/master/doc/generate_command_reference.py

However it might be better to switch to our own hand-written documentation for clarification.

**Comment by Mic92** [comment]
Thanks!

**Comment by DivineDominion** [comment]
Maybe it could make sense to have a CI script for validation, like a Peril/Dangerfile.

E.g.:

- given the latest check from upstream was commit hash `abc1234`
- download upstream changes after `abc1234`
- script produces notification about diffs inside merge requests
- maintainers decide whether to respond to this or not, e.g. adjust documentation or leave it unchanged
- either way, new upstream commit hash `def8765` is stored (For later reference to avoid being notified about the same diffs time and again)

This could run for all release branches/tags with Travis. Doesn't have to be for every PR.

The least complicated set-up in this direction would be running a GitHub bot/app on release branches/tags or PRs to print a reminder like "Upstream docs were updated since last release" without any details if the docs weren't touched.

**Comment by Mic92** [comment]
They actually switched to restructured text from docbook:

https://github.com/MusicPlayerDaemon/MPD/blob/master/doc/protocol.rst

This means that the current script no longer work anyway.

**Pull request merged**
