### PR TITLE
Grouping count command enhancement

### LINKED ISSUE #50: Grouping count command
The grouping version of count command behave unexpectedly IMHO:
```python
>>> cli = mpd.MPDClient()
>>> cli.connect(host='/run/mpd/socket', port=42)
>>> cli.count('group', 'albumartist')
{'albumartist': ['art00', 'art01',…], 
 'playtime': ['123', '321', …],
 'songs': ['1', '2',…]}
>>> #  idem with:
>>> cli.count('genre', 'Rock', 'group', 'albumartist')
```
I would expect a list of object of that kind instead:
```python
>>> cli.count('group', 'albumartist')
[ {'albumartist': 'art00', 'playtime': '123', 'songs': '1'},
  {'albumartist': 'art01', 'playtime': '321', 'songs': '2'},
…]
```
This object does not require extra processing to link grouping values with its playtime/songs stats.

I had a quick look at the raw MPD output, I think this might be tricky since the delimiter changes depending on the function signature. I don't have a straight forward solution to submit.

That's it
Thanks for your work

### PR DESCRIPTION
**Pull request by mxjeff**
Should close #50

### CODE REVIEW

**Comment by multani** [comment]
I had a really quick look at this, and the change looks interesting to add in.
However, that's technically speaking a incompatibility change since the result of the count command is different. There should be a document to update in the doc/ directory to explain the change, can you update it? We should also do something about the version number when releasing this, I guess.

Additionally, there're some unit tests in the repository, that would be awesome if you could turn your example into tests!

I can give a more proper look someday next week, if someone else doesn't take this over :)

**Comment by mxjeff** [comment]
Alright I'll try to take time to complete and rework the pull request :-)

**Comment by multani** [comment]
You could have let this pull request opened and just update your branch as needed, my comment wasn't meant for you to close this and start all over again :) Sorry if you took it this way, that wasn't my intention.

(FYI, doing so allows to keep track of the comments, the modifications, and see what's being worked on.)

**Comment by mxjeff** [comment]
Humm, sorry. I'm not really used to github process.

I'll reopen the PR, it makes sense indeed to work on this thread of comment.

Thanks for the heads up :-)

**Comment by mxjeff** [comment]
I've added the relevant unit test.

I'm not that confident with documentation, I'de rather leave editing to somebody else with better english/reST/sphinx skills.

Changes are rather simple from the API point of view (though the output format changes). Comments on #50 and example provided in the pull request are self explanatory I think.

**Comment by mxjeff** [comment]
I've just noticed grouping is available for list command as well (cf. #53).

I believe a better solution can solve both issues, this pull request might be obsolete then.

I'll try to come up with a better solution for count and list.

**Comment by mxjeff** [comment]
I believe a way to go would be to expose command's argument in ``fetch_`` methods (``retval`` in ``_execute`` method).

It means **changing signatures for all ``_fetch_*`` methods** but it would ease a lot for these cases where MPD answer's format in conditioned by commands arguments.

That's just an idea, I haven't been through all the code and I might have missed some side effects.

**Comment by Mic92** [comment]
A different solution would be to a create new method just for grouping.

**Comment by Mic92** [comment]
The function signatures could look like this:

```
 def count(self, tag, needle, group=None):
     pass

 def list(self, _type, *args, group=None):
     pass
```

**Comment by Mic92** [comment]
This has also the advantage, that the group key is known, we do not have to maintain a list of possible group keys.

**Comment by mxjeff** [comment]
You mean not going through the ``mpd._commands`` abstraction and define explicit methods ``count``/``list`` in MPDClient object? As it's done for noidle for ex.?

I tried to avoid that kind of solutions as it breaks the current design of the module, but I might be wrong, I'm far from a software architect :D

**Comment by Mic92** [comment]
If mpd adds more keyword style arguments, it might be worth to extend the current metaprogramming done with mpd._commands. But currently I think it is easier to just add the methods manually, because the response type changes depending on the arguments, which the current system was not built for.

**Comment by Mic92** [comment]
closed through lack of activity.

**Pull request closed without merging**
