### PR TITLE
asyncio: Update tests to cover more

### PR DESCRIPTION
**Pull request by chrysn**
These changes remove a minor line of cruft that's obsolete after #134 (which this practically depends on), and add to the tests to cover the code that was questionable for possibly reintroducing the #117 bug.

Test coverage goes up from 58% to 69% for that file in the py39 tests I ran.

### CODE REVIEW

**Comment by chrysn** [comment]
Just before I (needlessly?) split out the test cases for asyncio: Is Python 2 going to be supported for longer, or is that on the way out anyway now that 3.5 went too?

**Comment by Mic92** [comment]
> Just before I (needlessly?) split out the test cases for asyncio: Is Python 2 going to be supported for longer, or is that on the way out anyway now that 3.5 went too?

I also want to drop it actually. I just have not found time to yet. If you have bits to be removed, we can already drop it.

**Comment by Mic92** [comment]
Let me remove python2.7 and pypy27 from CI.

**Comment by chrysn** [comment]
The changes in here are neither urgent nor should get stale easily; their primary contribution is that with this I have better confidence in #134 being correct (which I obtained with the original asyncio branch by manually testing it during development).

The concrete thing that's making the Python2 branches fail is that the tests now use async syntax -- that was not an issue with the async module itself (that's only imported by the user), but is here where there's new async code in the tests.

I'm just adding a commit to remove them from CI (and belay further text because we seem to be doing the same concurrently).

**Comment by chrysn** [comment]
Rebased on your Python 2 removal branch (with some additional Python 2 cleanup steps from when we overlapped).

**Review by Mic92 — APPROVED** [review]
Code looks good to me. Anything else you want to change?

**Comment by chrysn** [comment]
I'd be good with this. There's a bit of Python 2 removal cleanup that could be done, but that shouldn't be here. Also, there's a few Python 3.10 deprecation warnings still, but I'd have to investigate whether removing them works with Python 3.6, so for now let's go with this.

By the way, I just found I had an example sitting in my checkout from when I originally added async, and it still works (but adding it now isn't too clever given that it relies on the gbulb bindings between asyncio and Gtk which are abandoned).

And thanks for keeping the async aprts around all the years even though you don't use them yourself!

**Comment by Mic92** [comment]
Thanks!

**Pull request merged**
